# A list of devices you want to take the screenshots from
devices([
   "iPhone 8",
   "iPhone 8 Plus",
   "iPhone SE",
   "iPhone 11",
   "iPad Pro (12.9-inch)",
   "iPad Pro (9.7-inch)",
 ])

scheme("paXanSnapshots")

output_directory("./screenshots")

clear_previous_screenshots(true)
